# Generated by Django 6.0.3 on 2026-03-20 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.CharField(help_text='QR code ID', max_length=255, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=255)),
                ('firmware_version', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DiskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('capacity', models.BigIntegerField(help_text='Capacity in bytes')),
            ],
        ),
        migrations.CreateModel(
            name='DiskHaver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('permission', models.CharField(choices=[('ADMIN', 'Admin'), ('VOLUNTEER', 'Volunteer'), ('USER', 'User')], default='USER', max_length=20)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiskHavings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('havings_type', models.CharField(choices=[('give', 'Give'), ('take', 'Take'), ('copyready', 'Copy Ready'), ('copysuccess', 'Copy Success'), ('copyfail', 'Copy Fail'), ('broken', 'Broken')], max_length=20)),
                ('datasource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.datasource')),
                ('disk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.disk')),
                ('disk_haver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.diskhaver')),
            ],
        ),
        migrations.AddField(
            model_name='disk',
            name='disk_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.diskmodel'),
        ),
    ]
