# Generated by Django 6.0.4 on 2026-04-10 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diskhaver',
            name='permission',
        ),
    ]
