# Generated by Django 6.0.7 on 2026-07-15 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_diskhaver_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duplicator',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('manufacturer', models.CharField(max_length=100)),
                ('slots_total', models.PositiveIntegerField(default=0)),
                ('slots_status', models.JSONField(blank=True, default=list)),
                ('year_in_service', models.PositiveIntegerField(default=2026)),
            ],
        ),
        migrations.CreateModel(
            name='ReplicationLog',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=20)),
                ('table_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('record_id', models.CharField(max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='datasource',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='datasource',
            name='required_interface',
            field=models.CharField(blank=True, default='All Interfaces', max_length=50),
        ),
        migrations.AddField(
            model_name='datasource',
            name='required_size_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='disk',
            name='copy_complete_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disk',
            name='copy_fail_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disk',
            name='copy_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disk',
            name='duplicator_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='disk',
            name='duplicator_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='disk',
            name='hd_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disk',
            name='hd_speed',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='disk',
            name='pickup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disk',
            name='received_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disk',
            name='source_requested',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.datasource'),
        ),
        migrations.AddField(
            model_name='disk',
            name='status',
            field=models.CharField(default='received', max_length=20),
        ),
        migrations.AlterField(
            model_name='diskmodel',
            name='capacity',
            field=models.BigIntegerField(help_text='Capacity in Terabytes'),
        ),
        migrations.CreateModel(
            name='DiskStatusLog',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('operator', models.CharField(default='System', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('disk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.disk')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
